Repository Team1559/2023-Charged-Up, pull requests merged in 2023-03, with the labels that each got.

#35 Update to latest WPILib and CTRE libs
  .vscode/settings.json
  vendordeps/Phoenix.json
Labels: Cleanup

#40 Add command triggers for all controller axes + default threshold
  src/main/java/frc/lib/DTXboxController.java
Labels: Controls

#39 Assign a 20% speed slow mode in teleop
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/SwerveTeleopDriveCommand.java
Labels: Controls

#44 Chassis acceleration limits + change arm pre-pickup
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/arm/Arm.java
  src/main/java/frc/robot/subsystems/arm/ArmSegment.java
  src/main/java/frc/robot/subsystems/grabber/GrabberClaw.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
Labels: Arm, Grabber, Swerve

#42 Update WPILib to 2023.4.2, CTRE libs to 23.0.10
  build.gradle
  vendordeps/Phoenix.json
Labels: Cleanup

#30 Add some basic auto routes
  .vscode/settings.json
  simgui.json
  src/main/java/frc/lib/SwerveTrajectoryGenerator.java
  src/main/java/frc/robot/AutoRouteChooser.java
  src/main/java/frc/robot/AutoRoutes.java
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/Vision.java
  src/main/java/frc/robot/commands/ScoreCommands.java
  src/main/java/frc/robot/commands/SwerveTeleopAlignToGridCommand.java
  src/main/java/frc/robot/commands/SwerveTeleopDriveCommand.java
  src/main/java/frc/robot/commands/SwerveTrajectoryCommand.java
  src/main/java/frc/robot/commands/TeleopWristAngleCommand.java
  src/main/java/frc/robot/subsystems/arm/Arm.java
  src/main/java/frc/robot/subsystems/arm/ArmSegment.java
  src/main/java/frc/robot/subsystems/grabber/GrabberClaw.java
  src/main/java/frc/robot/subsystems/grabber/GrabberWrist.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
Labels: Autonomous

#46 Merge all changes before RIT to create a clean working branch at competition
  src/main/java/frc/robot/AutoRoutes.java
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ScoreCommands.java
  src/main/java/frc/robot/commands/SwerveTeleopDriveCommand.java
  src/main/java/frc/robot/subsystems/arm/Arm.java
  src/main/java/frc/robot/subsystems/grabber/GrabberWrist.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
Labels: Cleanup

#53 Auto route cleaning
  simgui.json
  src/main/java/frc/robot/AutoRouteChooser.java
  src/main/java/frc/robot/AutoRoutes.java
Labels: Autonomous, Cleanup
